In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [5]:
#Create tensors with tf.constant()
scalar=tf.constant(7)

In [7]:
scalar
#Checking the datatype of tensors

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
scalar.ndim
#Checking the number of dimensions of tensors

0

In [11]:
vector=tf.constant([10,10])


In [12]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
vector.ndim

1

In [14]:
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [15]:
matrix.ndim

2

In [16]:
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16)

In [17]:
another_matrix.ndim

2

In [18]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
tensor=tf.constant([[[1,2,3],[4,5,6]],
                     [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])

In [20]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

In [24]:
#Create the same tensor with tf.Variable used as above
variable=tf.Variable


In [25]:
variable

tensorflow.python.ops.variables.Variable

In [26]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [30]:
changeable_tensor[0].assign(11)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>

In [31]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>

In [41]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
# random_1
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the orders of elements in a tensor

In [43]:
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [44]:
not_shuffled.ndim

2

In [54]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [58]:
tensor1=tf.constant([[10,7],[3,4]])


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [66]:
tf.random.set_seed(7)
tf.random.shuffle(tensor1,seed=7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>